---
name: "ci"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  spec:
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - "3.2"
          - "3.3"
          - "3.4"
    name: "spec (ruby ${{ matrix.ruby_version }})"
    uses: "puppetlabs/cat-github-actions/.github/workflows/gem_ci.yml@main"
    secrets: "inherit"
    with:
      rake_task: "spec"
      ruby_version: ${{ matrix.ruby_version }}

  build:
    needs: "spec"
    runs-on: "ubuntu-latest"
    name: "Verify gem builds"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: "Verify gem builds"
        run: "gem build --strict --verbose *.gemspec"

  tests:
    needs:
      - "spec"
      - "build"
    runs-on: "ubuntu-latest"
    name: "Test suite"
    steps:
      - run: "echo Test suite completed"
